SUPABASE_URL = "https://nwhsnymzihkqtlufiafu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53aHNueW16aWhrcXRsdWZpYWZ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Nzg0MTYzMSwiZXhwIjoyMDYzNDE3NjMxfQ.dqA2B9jKEf_YniTmIme9LeSQZF3pDTDHKw7DH4yZLeM"  
ADMIN_PASSWORD = "RecordJuiceSearch$_81"  
