SUPABASE_URL = "https://nwhsnymzihkqtlufiafu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53aHNueW16aWhrcXRsdWZpYWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDE2MzEsImV4cCI6MjA2MzQxNzYzMX0.7ShjmnX6_cY2H-Aj3eHF_23BP4D0tUS5wgoDBq9_3oE"  
ADMIN_PASSWORD = "RecordJuiceSearch$_81"  
